// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSq31SbMF-Tq7AA81KQMas64V-tHdNCYg',
    appId: '1:473845136222:web:44ff9411bd2c86bc6a2dcf',
    messagingSenderId: '473845136222',
    projectId: 'boda-m-a-46b11',
    authDomain: 'boda-m-a-46b11.firebaseapp.com',
    storageBucket: 'boda-m-a-46b11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGoBY4Ks1N2MP5ebOW41mpyIcAdmZ6HXM',
    appId: '1:473845136222:android:66b124c917329af56a2dcf',
    messagingSenderId: '473845136222',
    projectId: 'boda-m-a-46b11',
    storageBucket: 'boda-m-a-46b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSy9B3cCTccASwpWprsOhIvz3eyKZ-UJk',
    appId: '1:473845136222:ios:25a80708ec6424616a2dcf',
    messagingSenderId: '473845136222',
    projectId: 'boda-m-a-46b11',
    storageBucket: 'boda-m-a-46b11.firebasestorage.app',
    iosBundleId: 'com.example.weddingInvitation',
  );
}
